name: Release Version

on:
  workflow_dispatch:
    inputs:
      github_user:
        description: 'The GitHub user to release with (Owner of the PAT)'
        required: true
        default: 'beckerjohannes'
      github_pat:
        description: 'A PAT that has the permission to push to protected branches.'
        required: true
      git_name:
        description: 'Name used for the release commits.'
        required: true
        default: 'Johannes Becker'
      git_mail:
        description: 'eMail used for the release commits.'
        required: true
        default: 'johannes.becker@4soft.de'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up JDK 11.0.2
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.2
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }} # Value of the GPG private key to import
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Configure Git user
        run: |
          git config user.email "${{ github.event.inputs.git_mail }}"
          git config user.name "${{ github.event.inputs.git_name }}"
          git remote set-url origin https://${{ github.event.inputs.github_user }}:${{ github.event.inputs.github_pat }}@github.com/${GITHUB_REPOSITORY}.git
      - name: Release with Maven
        run: |
          mvn -e -P release -B -s .mvn/release.settings.xml gitflow:release --file pom.xml
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_CENTRAL_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          OSSRH_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
